import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import icon from "../public/canopy.jpg";
import canopy from "../public/canopy.jpg";
import Logo from "../public/logo.jpg";
import Img01 from "../public/undraw_on_the_way_re_swjt.svg";
import Link from "next/link";
import { Fragment } from "react";
import { Disclosure, Menu, Transition } from "@headlessui/react";
import { Bars3Icon, BellIcon, XMarkIcon } from "@heroicons/react/24/outline";
import Header from "./Header";
import Footer from "./Footer";
import News from "./News";
import Deal from "./deal";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Rent On/東京のキャノピー・バイクレンタル</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/react.svg" />
      </Head>
      <Header />
      <main>
        <div className="mx-auto max-w-7xl py-6 sm:px-6 lg:px-8">
          <section className="text-gray-700">
            <div className="container flex mx-auto flex-col md:flex-row items-center px-5 py-20">
              <div className="md:w-1/2 flex-grow lg:pr-24 md:pr-16 text-center mb-16 md:text-left">
                <h1 className="sm:text-6xl text-3xl mb-4 font-medium text-gray-900">
                  <p className="mt-8 text-2xl">キャノピーの新レンタルサービス</p>
                  <p className="mt-8 text-sm text-gray-500">世田谷区、品川区、大田区、目黒区、港区、中央区、千代田区、江東区、川崎市</p>
                  <br />
                  月額40,000円のサブスク
                  <br />
                  追加料金なし、保険コミコミ
                </h1>
                <p className="mb-8 leading-relaxed">
                  Pro Shipperとしての選択肢
                  雨天でも出前館、Uberで最大収入を効率良くあげる
                </p>
                <div>
                  <button className="mx-auto lg:mx-auto text-white bg-[#0369a1] border-0 py-2 px-6 shadow-lg focus:shadow-outline hover:scale-105 transform transition duration-300 ease-in-out focus:outline-none hover:bg-[#7dd3fc] rounded text-lg">
                    はじめる
                  </button>
                </div>
              </div>
              <div className="lg:max-w-lg lg:w-full md:w-1/2 w-5/6">
              <News />
                <Image
                  src={canopy}
                  className="object-cover object-center rounded m-auto mt-5"
                  alt=""
                />
              </div>
            </div>
          </section>
       
          <section className="bg-white border-b py-8">
            <div className="container mx-auto flex flex-wrap pt-4 pb-12">
              <h2 className="w-full my-2 text-5xl font-bold leading-tight text-center text-[#0369a1]">
                3つの特徴
              </h2>
              <div className="w-full mb-4">
                <div className="h-1 mx-auto gradient w-64 opacity-25 my-0 py-0 rounded-t"></div>
              </div>
              <div className="w-full md:w-1/3 p-6 flex flex-col flex-grow flex-shrink">
                <div className="flex-1 bg-white rounded-t rounded-b-none overflow-hidden shadow">
                  <a
                    href="#"
                    className="flex flex-wrap no-underline hover:no-underline"
                  >
                    <p className="w-full text-gray-600 text-xs md:text-sm px-6">
                      追加オプションなし、修理日無償
                    </p>
                    <div className="w-full font-bold text-xl text-gray-800 px-6">
                      業界最安値 オイル交換、保険コミコミ月額40,000円
                    </div>
                    <p className="text-gray-800 text-base px-6 mb-5">
                      対人、対物自賠責保険が無制限。オイル交換やメンテナンス代も月額に含まれています。*ガソリン代は自己負担となります。
                    </p>
                  </a>
                </div>
                <div className="flex-none mt-auto bg-white rounded-b rounded-t-none overflow-hidden shadow p-6">
                  <div className="flex items-center justify-start">
                    <button className="mx-auto lg:mx-auto text-white bg-[#0369a1] border-0 py-2 px-6 shadow-lg focus:shadow-outline hover:scale-105 transform transition duration-300 ease-in-out focus:outline-none hover:bg-[#7dd3fc] rounded text-lg">
                      はじめる
                    </button>
                  </div>
                </div>
              </div>
              <div className="w-full md:w-1/3 p-6 flex flex-col flex-grow flex-shrink">
                <div className="flex-1 bg-white rounded-t rounded-b-none overflow-hidden shadow">
                  <a
                    href="#"
                    className="flex flex-wrap no-underline hover:no-underline"
                  >
                    <p className="w-full text-gray-600 text-xs md:text-sm px-6">
                      来店不要
                    </p>
                    <div className="w-full font-bold text-xl text-gray-800 px-6">
                      簡単な手続き、電子契約、クレカ払い可
                    </div>
                    <p className="text-gray-800 text-base px-6 mb-5">
                      来社不要。Webだけで契約。クレジットカードで支払い可能。契約書もPDFファイルの入力とサインだけ。ご希望の納車場所までキャノピーをお届けします。
                    </p>
                  </a>
                </div>
                <div className="flex-none mt-auto bg-white rounded-b rounded-t-none overflow-hidden shadow p-6">
                  <div className="flex items-center justify-center">
                    <button className="mx-auto lg:mx-auto text-white bg-[#0369a1] border-0 py-2 px-6 shadow-lg focus:shadow-outline hover:scale-105 transform transition duration-300 ease-in-out focus:outline-none hover:bg-[#7dd3fc] rounded text-lg">
                      はじめる
                    </button>
                  </div>
                </div>
              </div>
              <div className="w-full md:w-1/3 p-6 flex flex-col flex-grow flex-shrink">
                <div className="flex-1 bg-white rounded-t rounded-b-none overflow-hidden shadow">
                  <a
                    href="#"
                    className="flex flex-wrap no-underline hover:no-underline"
                  >
                    <p className="w-full text-gray-600 text-xs md:text-sm px-6">
                      途中解約可!購入も可能!
                    </p>
                    <div className="w-full font-bold text-xl text-gray-800 px-6">
                      初心者でも安心。スマホホルダー、Box付き
                    </div>
                    <p className="text-gray-800 text-base px-6 mb-5">
                      大容量Boxとスマホホルダーが標準装備。また、初めて乗る方には、丁寧に運転方法、注意点をレクチャーいたします。
                      私達のサービスには、よくある追加オプションなどは一切ございません。
                      走行距離制限などもございません。1日のレンタル料1,500円からでも貸出可能です。
                    </p>
                  </a>
                </div>
                <div className="flex-none mt-auto bg-white rounded-b rounded-t-none overflow-hidden shadow p-6">
                  <div className="flex items-center justify-end">
                    <button className="mx-auto lg:mx-auto text-white bg-[#0369a1] border-0 py-2 px-6 shadow-lg focus:shadow-outline hover:scale-105 transform transition duration-300 ease-in-out focus:outline-none hover:bg-[#7dd3fc] rounded text-lg">
                      はじめる
                    </button>
                  </div>
                </div>
              </div>
            </div>
          </section>

          <div className="text-gray-700 border-t border-gray-200"></div>

          <section className="bg-white border-b py-8">
            <div className="container max-w-5xl mx-auto m-8 ">
              <h2 className="w-full my-2 text-5xl font-bold leading-tight text-center text-gray-800">
                Pro Shipperとしての選択肢
              </h2>
              <div className="w-full mb-4">
                <div className="h-1 mx-auto gradient w-64 opacity-25 my-0 py-0 rounded-t"></div>
              </div>
              <div className="flex flex-wrap bg-[#7dd3fc]">
                <div className="w-5/6 sm:w-1/2 p-6">
                  <h3 className="text-3xl text-gray-800 font-bold leading-none mb-3">
                    自転車からバイクでデリバリーに挑戦したい方！
                  </h3>
                  <p className="text-gray-600 mb-8">
                    週末だけ借りるなど、気楽にレンタルできます。また、自転車からバイクでデリバリーを試してみたい方にはオススメです。
                    <br />
                    <br />
                    {/* Images from:
                    <a
                      className="text-pink-500 underline"
                      href="https://undraw.co/"
                    >
                      undraw.co
                    </a> */}
                  </p>
                </div>
                <div className="w-full sm:w-1/2 p-6">
                  <Image
                    src={Img01}
                    className="w-full h-full object-cover"
                    alt=""
                  />
                </div>
              </div>
              <div className="flex flex-wrap flex-col-reverse sm:flex-row bg-[#93c5fd]">
                <div className="w-full sm:w-1/2 p-6 mt-6">
                  <Image
                    src={Img01}
                    className=" h-full object-cover w-5/6 sm:h-64 mx-auto"
                    alt=""
                  />
                </div>
                <div className="w-full sm:w-1/2 p-6 mt-6">
                  <div className="align-middle">
                    <h3 className="text-3xl text-gray-800 font-bold leading-none mb-3">
                      4万ポッキリ。気にいれば6カ月以上レンタルされた方に20万円で売却も可能
                    </h3>
                    <p className="text-gray-600 mb-8">
                      1カ月4万円以上かかりません。保険代も弊社が負担しております。ガソリン代のみお支払いください。
                      6カ月以上レンタルされた方には、20万円で売却できます!乗ってみて気に入れば愛車にするのも選択肢です!
                      <br />
                      <br />
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </section>
        </div>
        <Deal/>
        <Footer />
      </main>
    </>
  );
}

          {/* <section className="container mx-auto text-center py-6 mb-12">
            <h2 className="w-full my-2 text-5xl font-bold leading-tight text-center text-white">
              キャノピーのサブスク
            </h2>
            <div className="w-full mb-4">
              <div className="h-1 mx-auto bg-white w-1/6 opacity-25 my-0 py-0 rounded-t"></div>
            </div>
            <h3 className="my-4 text-3xl leading-tight">
              月1万5000円で借りれる
            </h3>
            <button className="mx-auto lg:mx-0 hover:underline bg-white text-gray-800 font-bold rounded-full my-6 py-4 px-8 shadow-lg focus:outline-none focus:shadow-outline transform transition hover:scale-105 duration-300 ease-in-out">
              お申込み
            </button>
          </section> */}

          {/* <div className="pt-24">
            <div className="container px-3 mx-auto flex flex-wrap flex-col md:flex-row items-center">
              <div className="flex flex-col w-full md:w-2/5 justify-center items-start text-center md:text-left">
                <p className="uppercase tracking-loose w-full">
                  What business are you?
                </p>
                <h1 className="my-4 text-5xl font-bold leading-tight">
                  Main Hero Message to sell yourself!
                </h1>
                <p className="leading-normal text-2xl mb-8">
                  Sub-hero message, not too long and not too short. Make it just
                  right!
                </p>
                <button className="mx-auto lg:mx-0 hover:underline bg-white text-gray-800 font-bold rounded-full my-6 py-4 px-8 shadow-lg focus:outline-none focus:shadow-outline transform transition hover:scale-105 duration-300 ease-in-out">
                  Subscribe
                </button>
              </div>

              <div className="w-full md:w-3/5 py-6 text-center">
                <Image className="w-full md:w-4/5 z-50" src={canopy} alt="" />
              </div>
            </div>
          </div>
          <div className="relative -mt-12 lg:-mt-24">
            <svg
              viewBox="0 0 1428 174"
              version="1.1"
              xmlns="http://www.w3.org/2000/svg"
            >
              <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                <g
                  transform="translate(-2.000000, 44.000000)"
                  fill="#FFFFFF"
                  fill-rule="nonzero"
                >
                  <path
                    d="M0,0 C90.7283404,0.927527913 147.912752,27.187927 291.910178,59.9119003 C387.908462,81.7278826 543.605069,89.334785 759,82.7326078 C469.336065,156.254352 216.336065,153.6679 0,74.9732496"
                    opacity="0.100000001"
                  ></path>
                  <path
                    d="M100,104.708498 C277.413333,72.2345949 426.147877,52.5246657 546.203633,45.5787101 C666.259389,38.6327546 810.524845,41.7979068 979,55.0741668 C931.069965,56.122511 810.303266,74.8455141 616.699903,111.243176 C423.096539,147.640838 250.863238,145.462612 100,104.708498 Z"
                    opacity="0.100000001"
                  ></path>
                  <path
                    d="M1046,51.6521276 C1130.83045,29.328812 1279.08318,17.607883 1439,40.1656806 L1439,120 C1271.17211,77.9435312 1140.17211,55.1609071 1046,51.6521276 Z"
                    id="Path-4"
                    opacity="0.200000003"
                  ></path>
                </g>
                <g
                  transform="translate(-4.000000, 76.000000)"
                  fill="#FFFFFF"
                  fill-rule="nonzero"
                >
                  <path d="M0.457,34.035 C57.086,53.198 98.208,65.809 123.822,71.865 C181.454,85.495 234.295,90.29 272.033,93.459 C311.355,96.759 396.635,95.801 461.025,91.663 C486.76,90.01 518.727,86.372 556.926,80.752 C595.747,74.596 622.372,70.008 636.799,66.991 C663.913,61.324 712.501,49.503 727.605,46.128 C780.47,34.317 818.839,22.532 856.324,15.904 C922.689,4.169 955.676,2.522 1011.185,0.432 C1060.705,1.477 1097.39,3.129 1121.236,5.387 C1161.703,9.219 1208.621,17.821 1235.4,22.304 C1285.855,30.748 1354.351,47.432 1440.886,72.354 L1441.191,104.352 L1.121,104.031 L0.457,34.035 Z"></path>
                </g>
              </g>
            </svg>
          </div> */}