import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import icon from "../public/canopy.jpg";
import canopy from "../public/canopy.jpg";
import Img01 from "../public/undraw_on_the_way_re_swjt.svg";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <div className="bg-[#f4f4f5]">
      <Head>
        <title>Rent On/東京のキャノピー・バイクレンタル</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/react.svg" />
      </Head>

      <header className="text-gray-700 bg-[#0369a1] border-b border-gray-200 fixed w-full">
        {/* md ... md以上の時にcssを適用 */}
        <div className="container mx-auto flex p-5 items-center md:flex-row flex-col">
          <Link href="/" className="font-medium text-gray-900 mb-4 md:mb-0">
            {/* <svg
              width="24"
              height="24"
              viewBox="0 0 24 24"
              fill="none"
              xmlns="http://www.w3.org/2000/svg"
            >
              <path
                d="M14.0636 8C14.6159 8 15.0636 7.55228 15.0636 7C15.0636 6.44772 14.6159 6 14.0636 6C13.5113 6 13.0636 6.44772 13.0636 7C13.0636 7.55228 13.5113 8 14.0636 8Z"
                fill="currentColor"
              />
              <path
                fill-rule="evenodd"
                clip-rule="evenodd"
                d="M13 3C15.1523 3 17.1281 3.7555 18.6768 5.01576L20.124 6.46299L18.8288 7.75818L18.828 7.75738L14.5854 12L18.2236 15.6383L18.2224 15.6396L20.1273 17.5445L18.7144 18.9575L18.7122 18.9553C17.1583 20.2329 15.1687 21 13 21C8.02944 21 4 16.9706 4 12C4 7.02944 8.02944 3 13 3ZM11.7569 12L17.2893 17.5323C16.1044 18.4523 14.6162 19 13 19C9.13401 19 6 15.866 6 12C6 8.13401 9.13401 5 13 5C14.6162 5 16.1045 5.54772 17.2893 6.46768L11.7569 12Z"
                fill="currentColor"
              />
            </svg> */}
            <span className="ml-3 text-xl text-white">Rent On</span>
          </Link>
          <nav className="flex items-center justify-center md:ml-auto text-base">
            <Link
              href="#about"
              className=" text-white mr-5 hover:text-blue-400 duration-300"
            >
              ご利用方法
            </Link>
            <Link
              href="/Fee"
              className="text-white mr-5 hover:text-blue-400 duration-300"
            >
              料金
            </Link>
            <Link
              href="/About"
              className=" text-white mr-5 hover:text-blue-400 duration-300"
            >
              会社概要
            </Link>
            <Link
              href="/Contact3"
              className=" text-white mr-5 hover:text-blue-400 duration-300"
            >
              お問い合わせ
            </Link>

            {/* <a href="#contact" className="hover:text-blue-400 duration-300">
            </a> */}
          </nav>
        </div>
      </header>

      <section id="home" className="text-gray-700">
        <div className="container flex mx-auto flex-col md:flex-row items-center px-5 py-20">
          <div className="md:w-1/2 flex-grow lg:pr-24 md:pr-16 text-center mb-16 md:text-left">
            <h1 className="sm:text-6xl text-3xl mb-4 font-medium text-gray-900">
              <p className="mt-8 text-lg">キャノピーのレンタル</p>
              <br />
              月額15,000円のサブスク
              <br />
              24時間いつでも、即納車
            </h1>
            <p className="mb-8 leading-relaxed">
              Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nesciunt
              dignissimos atque voluptate blanditiis necessitatibus reiciendis
              tenetur amet? Repudiandae, cupiditate illum.
            </p>
            <div>
              <button className="text-white bg-[#0369a1] border-0 py-2 px-6 focus:outline-none hover:bg-[#7dd3fc] rounded text-lg">
                get started
              </button>
            </div>
          </div>
          <div className="lg:max-w-lg lg:w-full md:w-1/2 w-5/6">
            <Image
              src={canopy}
              className="object-cover object-center rounded m-auto"
              alt=""
            />
          </div>
        </div>
      </section>

      <section id="about" className="text-gray-700 border-t border-gray-200">
        <div className="container px-5 py-24 mx-auto">
          <div className="text-center mb-20">
            <h1 className="sm:text-3xl text-2xl font-medium mb-2 text-gray-900">
              Pro Shipperとしての選択肢
            </h1>
            <p className="pb-10">出前館、Uberで最大収入を効率良くあげる</p>
            <p>
              Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dicta,
              ad debitis praesentium quis dolore adipisci deleniti. Fugit non
              magni dolorem! Facere debitis rerum qui ut fuga, ullam, ad vitae
              explicabo et ipsa amet consequatur ipsum iure quibusdam numquam
              illo ipsam reiciendis rem sapiente architecto exercitationem,
              labore quaerat. Dolore numquam quam repellendus saepe culpa
              distinctio maiores soluta, pariatur quae alias velit nisi
              corrupti, quod magnam eius. Necessitatibus architecto nobis ipsa,
              excepturi voluptatibus eum velit cum sequi possimus harum sunt
              commodi cumque sint. Enim tempora minima sapiente omnis, qui
              facilis! Sequi, ab ut facere excepturi molestias ipsa, reiciendis
              quisquam, sed eos magni aliquid explicabo. Est vel sequi cum ipsa
            </p>
          </div>
          
          <div className="flex -m-4 flex-wrap">
            <div className="md:w-1/3 p-4">
              <div className="bg-gray-100 h-full p-8 rounded-lg ">
                <div className="flex items-center mb-3">
                  <div className="bg-[#0284c7] text-white rounded-full w-8 h-8 flex justify-center items-center mr-3">
                    <svg
                      width="24"
                      height="24"
                      viewBox="0 0 24 24"
                      fill="none"
                      xmlns="http://www.w3.org/2000/svg"
                    >
                      <path
                        fill-rule="evenodd"
                        clip-rule="evenodd"
                        d="M19 9C19 11.3787 17.8135 13.4804 16 14.7453V22H13.4142L12 20.5858L10.5858 22H8V14.7453C6.18652 13.4804 5 11.3787 5 9C5 5.13401 8.13401 2 12 2C15.866 2 19 5.13401 19 9ZM17 9C17 11.7614 14.7614 14 12 14C9.23858 14 7 11.7614 7 9C7 6.23858 9.23858 4 12 4C14.7614 4 17 6.23858 17 9ZM10 19.7573L12 17.7573L14 19.7574V15.7101C13.3663 15.8987 12.695 16 12 16C11.305 16 10.6337 15.8987 10 15.7101V19.7573Z"
                        fill="currentColor"
                      />
                    </svg>
                  </div>
                  <h2 className="text-gray-900 text-lg font-medium">
                    業界最安値　オイル交換台、保険コミコミ月額
                    <span className="text-[#0284c7]">15,000円</span>
                  </h2>
                </div>
                <div className="#">
                  <p className="leading-relaxed text-base">
                    対人、対物自賠責保険が無制限。オイル交換やメンテナンス代も月額に含まれています。*ガソリン代は自己負担となります。
                  </p>
                </div>
              </div>
            </div>
            <div className="md:w-1/3 p-4">
              <div className="bg-gray-100 h-full p-8 rounded-lg">
                <div className="flex items-center mb-3">
                  <div className="bg-[#0284c7] text-white rounded-full w-8 h-8 flex justify-center items-center mr-3">
                    <svg
                      width="24"
                      height="24"
                      viewBox="0 0 24 24"
                      fill="none"
                      xmlns="http://www.w3.org/2000/svg"
                    >
                      <path
                        fill-rule="evenodd"
                        clip-rule="evenodd"
                        d="M19 9C19 11.3787 17.8135 13.4804 16 14.7453V22H13.4142L12 20.5858L10.5858 22H8V14.7453C6.18652 13.4804 5 11.3787 5 9C5 5.13401 8.13401 2 12 2C15.866 2 19 5.13401 19 9ZM17 9C17 11.7614 14.7614 14 12 14C9.23858 14 7 11.7614 7 9C7 6.23858 9.23858 4 12 4C14.7614 4 17 6.23858 17 9ZM10 19.7573L12 17.7573L14 19.7574V15.7101C13.3663 15.8987 12.695 16 12 16C11.305 16 10.6337 15.8987 10 15.7101V19.7573Z"
                        fill="currentColor"
                      />
                    </svg>
                  </div>
                  <h2 className="text-gray-900 text-lg font-medium">
                    <span className="text-[#0284c7]">簡単な手続き</span>、電子契約、クレカ払い可
                  </h2>
                </div>
                <div className="#">
                  <p className="leading-relaxed text-base">
                   来社不要。Webだけで契約。クレジットカードで支払い可能。契約書もPDFファイルの入力とサインだけ。ご希望の納車場所までキャノピーをお届けします。
                  </p>
                </div>
              </div>
            </div>
            <div className="md:w-1/3 p-4">
              <div className="bg-gray-100 h-full p-8 rounded-lg">
                <div className="flex items-center mb-3">
                  <div className="bg-[#0284c7] text-white rounded-full w-8 h-8 flex justify-center items-center mr-3">
                    <svg
                      width="24"
                      height="24"
                      viewBox="0 0 24 24"
                      fill="none"
                      xmlns="http://www.w3.org/2000/svg"
                    >
                      <path
                        fill-rule="evenodd"
                        clip-rule="evenodd"
                        d="M19 9C19 11.3787 17.8135 13.4804 16 14.7453V22H13.4142L12 20.5858L10.5858 22H8V14.7453C6.18652 13.4804 5 11.3787 5 9C5 5.13401 8.13401 2 12 2C15.866 2 19 5.13401 19 9ZM17 9C17 11.7614 14.7614 14 12 14C9.23858 14 7 11.7614 7 9C7 6.23858 9.23858 4 12 4C14.7614 4 17 6.23858 17 9ZM10 19.7573L12 17.7573L14 19.7574V15.7101C13.3663 15.8987 12.695 16 12 16C11.305 16 10.6337 15.8987 10 15.7101V19.7573Z"
                        fill="currentColor"
                      />
                    </svg>
                  </div>
                  <h2 className="text-gray-900 text-lg font-medium">
                    <span className="text-[#0284c7]">初心者でも安心</span>。スマホホルダー、Box付き
                  </h2>
                </div>
                <div className="#">
                  <p className="leading-relaxed text-base">
                   弊社のキャノピーには、大容量Boxとスマホホルダーが標準装備。また、初めて乗る方には、丁寧に運転方法、注意点をレクチャーいたします。
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      <section id="skill" className="text-gray-700 border-t border-gray-200">
        <div className="flex container px-5 py-24 mx-auto flex-wrap">
          <div className="rounded w-full mb-10 lg:w-1/2 lg:mb-0">
            <Image src={Img01} className="w-full h-full object-cover" alt="" />
          </div>
          <div className="lg:py-6 lg:pl-12 lg:text-left lg:w-1/2 w-full">
            <h1 className="sm:text-3xl text-2xl font-medium text-gray-900 mb-10">
              
            </h1>
            <div className="">
              <div className="w-full">
                <h2>HTML</h2>
                <div className="shadow w-full bg-green-100 mt-2"></div>
              </div>
            </div>
          </div>
        </div>
      </section>

      <section id="skill" className="text-gray-700 border-t border-gray-200">
        <div className="flex container px-5 py-24 mx-auto flex-wrap">
          <div className="rounded w-full mb-10 lg:w-1/2 lg:mb-0">
            <Image src={Img01} className="w-full h-full object-cover" alt="" />
          </div>
          <div className="lg:py-6 lg:pl-12 lg:text-left lg:w-1/2 w-full">
            <h1 className="sm:text-3xl text-2xl font-medium text-gray-900 mb-10">
              
            </h1>
            <div className="">
              <div className="w-full">
                <h2>HTML</h2>
                <div className="shadow w-full bg-green-100 mt-2"></div>
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>
  );
}
