import { NextApiRequest, NextApiResponse } from "next";
import React, { useRef, useState } from "react";
import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import icon from "../public/canopy.jpg";
import canopy from "../public/canopy.jpg";
import Logo from "../public/logo.jpg";
import Img01 from "../public/undraw_on_the_way_re_swjt.svg";
import Link from "next/link";
import { Fragment } from "react";
import { Disclosure, Menu, Transition } from "@headlessui/react";
import { Bars3Icon, BellIcon, XMarkIcon } from "@heroicons/react/24/outline";
import Header from "./Header";
import Footer from "./Footer";

const features = [
  {
    name: "1⃣Web手続きor電話手続き",
    description: "Designed by Good Goods, Inc.",
  },
  {
    name: "3⃣レンタル料金のお振込みorクレジット決済",
    description: "運転免許証の提出、またコピーを取らせていただきます",
  },
  {
    name: "2⃣レンタル期間の選択(1カ月or1日)",
    description: '6.25" x 3.55" x 1.15"',
  },
  {
    name: "4⃣ご希望の受け渡し場所へ納車",
    description: "Hand sanded and finished with natural oil",
  },
];

export default function ToUse() {
  return (
    <>
      <Head>
        <title>Rent On/東京のキャノピー・バイクレンタル</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/react.svg" />
      </Head>
      <Header />
      <div className="bg-white mx-auto grid max-w-2xl grid-cols-1 items-center gap-y-16 gap-x-8 py-24 px-4 sm:px-6 sm:py-32 lg:max-w-7xl lg:grid-cols-1 lg:px-8">
        <div>
          <h2 className="text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl">
            ご利用手順
          </h2>
          <p className="mt-4 text-gray-500">
            レンタルをご利用される方には、契約書を交わしていただきます。2通りの方法がございます。
          </p>
          <p className="mt-4 text-gray-500">
            ➊来店して、契約書を交わす(運転免許証の確認)
          </p>
          <p className="mt-4 text-gray-500">➋オンラインで契約書を交わす</p>
          <div className="ml-20 mt-10">
            <svg
              xmlns="http://www.w3.org/2000/svg"
              fill="none"
              viewBox="0 0 24 24"
              stroke-width="1.5"
              stroke="currentColor"
              className="w-6 h-6"
            >
              <path
                stroke-linecap="round"
                stroke-linejoin="round"
                d="M19.5 13.5L12 21m0 0l-7.5-7.5M12 21V3"
              />
            </svg>
          </div>

          <dl className="mt-16 grid grid-cols-1 gap-x-6 gap-y-10 sm:grid-cols-2 sm:gap-y-16 lg:gap-x-8">
            {features.map((feature) => (
              <div
                key={feature.name}
                className="border-t border-indigo-800 pt-4"
              >
                <dt className="font-medium text-gray-900">{feature.name}</dt>
                <dd className="mt-2 text-sm text-gray-500 ">
                  {feature.description}
                </dd>
                <div
                  key={feature.name}
                  className="border-l border-emerald-400"
                ></div>
              </div>
            ))}
          </dl>
        </div>
        <div className="flex justify-center mt-10"><button className="mx-auto lg:mx-auto text-white bg-[#0369a1] border-0 py-2 px-6 shadow-lg focus:shadow-outline hover:scale-105 transform transition duration-300 ease-in-out focus:outline-none hover:bg-[#7dd3fc] rounded text-lg">はじめる</button></div>
      </div>

      <Footer />
    </>
  );
}
